CREATE DATABASE %%DBNAME%%
DEFAULT CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

GRANT SELECT,INSERT,UPDATE,DELETE,CREATE,CREATE TEMPORARY TABLES,
DROP,INDEX,ALTER,LOCK TABLES
ON %%DBNAME%%.*
TO '%%DBUSER%%'@'%';
